### ISSUE TITLE
please post screenshots of the macro in action...

### ISSUE THREAD

**Issue by luzpaz** [vectronic/freecad-legify-macros#1]
Also if you feel inspired to share with the FC community, you could post in the Users Showcase sub-forum: https://forum.freecadweb.org/viewforum.php?f=24

**Comment by luzpaz** [comment]
BTW @vectronic  
is there a usecase for this macro to work as requested in this forum thread: https://forum.freecadweb.org/viewtopic.php?f=3&t=31591

**Comment by vectronic** [comment]
Hi @luzpaz, apologies for not replying sooner, I've been dealing with real life stuff around moving house.

Answer to first comment: I do indeed intend to share with the FC community, just a couple of bugs and tweaks I want to do first. I'll also drop some screenshots in the repo.

Answer to second question: (which I see you have got suitable info from the forum in the meantime). What I'm working on is just a macro for drawing a single brick (a hay bale in your case), I'm dealing with assemblies at all (yet).

**Comment by vectronic** [comment]
I've added screenshots and cut a v0.1.0 release. Announced here: https://forum.freecadweb.org/viewtopic.php?f=24&t=33568
