### ISSUE TITLE
feature request: height 3+ support?

### ISSUE THREAD

**Issue by minger0** [vectronic/freecad-legify-macros#3]
there are existing blocks higher than 3
what is the reason to limit to 3? the result may not always be satisfying, but for 1x1x9 e.g. it would be good enough

**Comment by vectronic** [comment]
I started this project with the intention of modelling real bricks as accurately as possible. For instance, I'm not sure how to render the internal structure of a 4 x 4 x 9 brick. 

I would need to look into whether it would be as simple as lifting constraints on the height to be 3+. I have been trying to use datum planes as much as possible so it might just 'magically work'.

I intend to give this project a bit more love in the next couple of months, so will look into it...

**Comment by vectronic** [comment]
Fixed in this release:

https://github.com/vectronic/freecad-legify-macros/releases/tag/v0.2.0
